name: CI Workflow

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js (or any other environment)
        uses: actions/setup-node@v2
        with:
          node-version: '14' # specify the node version you need

      - name: Install dependencies
        run: npm install # replace with your dependency installation command

      - name: Run tests
        run: npm test # replace with your test command

      - name: Build project
        run: npm run build # replace with your build command

      - name: Deploy (if applicable)
        run: echo "Deploy steps go here" # replace with your deploy command
